// src/components/Family/FiltersPopup.vue
<template>
	<a-modal
		v-model:visible="visible"
		title="Filters"
		@cancel="emits('close')"
		:loading="loading"
		:disabled="true"
	>
		<div class="input-form">
			<p>Categories to filter</p>
			<a-select
				class="full-width"
				ref="select"
				v-model:value="filters.categoryIds"
				style="margin-top: 10px"
				:mode="'multiple'"
			>
				<a-select-option
					v-for="category in categories"
					:key="category.id"
					:value="category.id"
					>{{ category.name }}</a-select-option
				>
			</a-select>
		</div>
		<template #footer>
			<a-button key="back" @click="emits('close')">Cancel</a-button>
			<a-button
				type="primary"
				danger
				@click="clearFilters"
				:disabled="!filters.categoryIds?.length"
				>Clear</a-button
			>
			<a-button key="submit" type="primary" :loading="loading" @click="handleOk"
				>Apply</a-button
			>
		</template>
	</a-modal>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { loading } from '../../services/utils';
import { useCategoryStore } from '../../stores/category';
import { CategoryType } from '../../models/category';
import { Filters } from './TransactionList.vue';

const props = defineProps<{
	type: CategoryType;
	visible: boolean;
	filters?: Filters;
}>();

const emits = defineEmits(['close', 'ok']);

const visible = ref<boolean>(false);
const filters = ref<Filters>(JSON.parse(JSON.stringify(props.filters)));
const category = ref('');

watch(
	() => props.visible,
	() => (visible.value = props.visible)
);

watch(
	() => visible.value,
	() => {
		if (!visible.value) emits('close');
	}
);

watch(
	() => props.type,
	() => (category.value = '')
);

watch(
	() => props.filters,
	() => {
		if (props.filters) filters.value = JSON.parse(JSON.stringify(props.filters));
	}
);

const allCategories = computed(() => useCategoryStore().categories);
const categories = computed(() => allCategories.value.filter(c => c.type === props.type));

const clearFilters = () => {
	filters.value = {};
	handleOk();
};
const handleOk = () => emits('ok', filters.value);
</script>

<style lang="scss" scoped>
.input-form {
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	align-items: flex-start;
}
</style>

// src/components/Family/FiltersPopup.tsx
import { useState, useEffect, useMemo } from 'react';
import { Button } from '../ui/button';
import { Checkbox } from '../ui/checkbox';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../ui/dialog';
import { useCategoryStore } from '../../stores/category';
import { CategoryType } from '../../models/category';
import { Filters } from './TransactionList';

interface Props {
	type: CategoryType;
	open: boolean;
	onOpenChange: (open: boolean) => void;
	filters: Filters;
	onApply: (filters: Filters) => void;
}

export default function FiltersPopup({ type, open, onOpenChange, filters: propFilters, onApply }: Props) {
	const [categoryIds, setCategoryIds] = useState<string[]>(propFilters.categoryIds || []);
	const allCategories = useCategoryStore(s => s.categories);
	const categories = useMemo(() => allCategories.filter(c => c.type === type), [allCategories, type]);

	useEffect(() => {
		setCategoryIds(propFilters.categoryIds || []);
	}, [propFilters]);

	const toggleCategory = (id: string) => {
		setCategoryIds(prev => prev.includes(id) ? prev.filter(c => c !== id) : [...prev, id]);
	};

	const handleOk = () => onApply({ categoryIds });
	const clearFilters = () => onApply({});

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>Filters</DialogTitle>
				</DialogHeader>
				<div className="flex flex-col gap-2 items-start">
					<p className="text-sm">Categories to filter</p>
					{categories.map(c => (
						<div key={c.id} className="flex items-center gap-2">
							<Checkbox checked={categoryIds.includes(c.id)} onCheckedChange={() => toggleCategory(c.id)} />
							<span className="text-sm">{c.name}</span>
						</div>
					))}
				</div>
				<DialogFooter>
					<Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
					<Button variant="destructive" onClick={clearFilters} disabled={!categoryIds.length}>Clear</Button>
					<Button onClick={handleOk}>Apply</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
