// src/components/Family/NewTransactionPopup.vue
<template>
	<a-modal
		v-model:visible="visible"
		:title="'New ' + type"
		@cancel="emits('close')"
		:loading="loading"
		:disabled="true"
	>
		<div class="input-form">
			<a-row>
				<p>Date</p>
				<a-input
					class="full-width"
					type="date"
					v-model:value="transaction.date"
					placeholder="Choose a date"
				/>
			</a-row>
			<a-row>
				<p>Description</p>
				<a-input
					class="full-width"
					type="text"
					v-model:value="transaction.description"
					placeholder="Enter a description"
				/>
			</a-row>
			<a-row>
				<p>Amount</p>
				<a-input-number
					class="full-width"
					v-model:value="transaction.amount"
					placeholder="Enter an amount"
					:min="0"
					:precision="2"
					addon-after="€"
				/>
			</a-row>
			<a-row class="full-width">
				<p>Category</p>
				<a-select class="full-width" ref="select" v-model:value="transaction.category">
					<a-select-option
						v-for="category in categories"
						:key="category.id"
						:value="category.id"
						>{{ category.name.toLowerCase() }}</a-select-option
					>
				</a-select>
			</a-row>
			<a-row class="full-width">
				<p>Tag</p>
				<a-select class="full-width" ref="select" v-model:value="transaction.tag">
					<a-select-option v-for="tag in tags" :key="tag.id" :value="tag.id">{{
						tag.name
					}}</a-select-option>
				</a-select>
			</a-row>
		</div>
		<template #footer>
			<a-button key="back" @click="emits('close')">Return</a-button>
			<a-button
				key="submit"
				type="primary"
				:loading="loading"
				@click="handleOk"
				:disabled="
					!transaction.amount ||
					!transaction.date ||
					!transaction.description ||
					!transaction.category
				"
				>Create</a-button
			>
		</template>
	</a-modal>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { ITransaction } from '../../models/transaction';
import {
	formatDate,
	loading,
	MONTHS,
	openNotificationWithIcon,
	setIsLoading,
} from '../../services/utils';
import { DataBaseClient } from '../../api/db';
import { useCategoryStore } from '../../stores/category';
import { useTagStore } from '../../stores/tag';

const props = defineProps<{
	visible: boolean;
	type: 'expense' | 'earning';
}>();

const emits = defineEmits(['close', 'ok']);

const visible = ref<boolean>(false);
const newTransaction = () => ({
	description: '',
	date: formatDate(new Date().toISOString()),
	category: '',
	type: props.type,
	month: MONTHS[new Date().getMonth()],
	year: new Date().getFullYear().toString(),
	tag: 'XB0kK9DnZIIEsPKsaWEB',
});

const transaction = ref<Partial<ITransaction>>(newTransaction());
const resetTransaction = () => (transaction.value = newTransaction());

watch(
	() => transaction.value.date,
	date => {
		if (date) {
			const dateObj = new Date(date);
			transaction.value.month = MONTHS[dateObj.getMonth()];
			transaction.value.year = dateObj.getFullYear().toString();
		}
	}
);
watch(
	() => props.visible,
	() => (visible.value = props.visible)
);

watch(
	() => visible.value,
	() => {
		if (!visible.value) emits('close');
	}
);

watch(
	() => props.type,
	() => resetTransaction()
);

const allCategories = computed(() => useCategoryStore().categories);
const categories = computed(() => allCategories.value.filter(c => c.type === props.type));
const tags = computed(() => useTagStore().tags);

const handleOk = () => {
	setIsLoading(true);
	const completeTransaction: ITransaction = transaction.value as ITransaction;
	DataBaseClient.Transaction.create(completeTransaction)
		.then(transaction => {
			openNotificationWithIcon(
				'success',
				'Success',
				'Transaction ' + transaction.description + ' saved'
			);
			resetTransaction();
			emits('close');
		})
		.catch(err => console.error(err))
		.finally(() => setIsLoading(false));
};

if (allCategories.value.length === 0) {
	setIsLoading(true);
	DataBaseClient.Category.get()
		.then(categories => {
			useCategoryStore().setCategories(categories);
		})
		.catch(err => console.error(err))
		.finally(() => setIsLoading(false));
}
</script>

<style lang="scss" scoped>
.input-form {
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	align-items: flex-start;
	gap: 0.75rem;
}
</style>

// src/components/Family/NewTransactionPopup.tsx
import { useState, useEffect, useMemo } from 'react';
import { CalendarDays, FileText, Tag as TagIcon, FolderOpen, Euro } from 'lucide-react';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Dialog, DialogContent } from '../ui/dialog';
import { formatDate, MONTHS, openNotificationWithIcon, setIsLoading } from '../../services/utils';
import { DataBaseClient } from '../../api/db';
import { useCategoryStore } from '../../stores/category';
import { useTagStore } from '../../stores/tag';
import { ITransaction } from '../../models/transaction';

interface Props {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	type: 'expense' | 'earning';
}

export default function NewTransactionPopup({ open, onOpenChange, type }: Props) {
	const newTransaction = (): Partial<ITransaction> => ({
		description: '',
		date: formatDate(new Date().toISOString()),
		category: '',
		type,
		month: MONTHS[new Date().getMonth()],
		year: new Date().getFullYear().toString(),
		tag: 'XB0kK9DnZIIEsPKsaWEB',
	});

	const [transaction, setTransaction] = useState<Partial<ITransaction>>(newTransaction());
	const allCategories = useCategoryStore(s => s.categories);
	const tags = useTagStore(s => s.tags);
	const categories = useMemo(() => allCategories.filter(c => c.type === type), [allCategories, type]);

	useEffect(() => {
		setTransaction(newTransaction());
	}, [type]);

	const updateField = (field: string, value: any) => {
		setTransaction(prev => {
			const updated = { ...prev, [field]: value };
			if (field === 'date' && value) {
				const dateObj = new Date(value);
				updated.month = MONTHS[dateObj.getMonth()];
				updated.year = dateObj.getFullYear().toString();
			}
			return updated;
		});
	};

	const handleOk = () => {
		setIsLoading(true);
		DataBaseClient.Transaction.create(transaction as ITransaction)
			.then(t => {
				openNotificationWithIcon('success', 'Success', 'Transaction ' + t.description + ' saved');
				setTransaction(newTransaction());
				onOpenChange(false);
			})
			.catch(err => console.error(err))
			.finally(() => setIsLoading(false));
	};

	const isDisabled = !transaction.amount || !transaction.date || !transaction.description || !transaction.category;
	const isExpense = type === 'expense';
	const accentColor = isExpense ? '#cf1322' : '#3f8600';

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent className="p-0 gap-0 overflow-hidden max-w-[360px] rounded-2xl border-0 shadow-2xl">
				{/* Colored header strip */}
				<div className="px-5 pt-5 pb-4" style={{ background: `linear-gradient(135deg, ${accentColor}12, ${accentColor}06)` }}>
					<div className="flex items-center gap-2 mb-3">
						<div className="h-2 w-2 rounded-full" style={{ backgroundColor: accentColor }} />
						<span className="text-xs font-semibold uppercase tracking-widest" style={{ color: accentColor }}>
							New {type}
						</span>
					</div>
					{/* Hero amount field */}
					<div className="flex items-baseline gap-1 justify-center">
						<input
							type="number"
							min={0}
							step={0.01}
							value={transaction.amount || ''}
							onChange={e => updateField('amount', parseFloat(e.target.value) || 0)}
							placeholder="0.00"
							className="bg-transparent border-none outline-none text-center text-4xl font-bold tracking-tight w-full placeholder:text-black/15"
							style={{ color: accentColor }}
						/>
						<Euro className="h-6 w-6 shrink-0 -ml-2 opacity-40" style={{ color: accentColor }} />
					</div>
				</div>

				{/* Form fields */}
				<div className="px-5 py-4 space-y-3">
					<div className="space-y-1.5">
						<Label className="text-xs text-muted-foreground flex items-center gap-1.5">
							<FileText className="h-3 w-3" /> Description
						</Label>
						<Input
							type="text"
							value={transaction.description || ''}
							onChange={e => updateField('description', e.target.value)}
							placeholder="What was it for?"
							className="h-10 bg-white/80 border-black/8 rounded-xl text-sm placeholder:text-muted-foreground/50"
						/>
					</div>

					<div className="grid grid-cols-2 gap-3">
						<div className="space-y-1.5">
							<Label className="text-xs text-muted-foreground flex items-center gap-1.5">
								<CalendarDays className="h-3 w-3" /> Date
							</Label>
							<Input
								type="date"
								value={transaction.date || ''}
								onChange={e => updateField('date', e.target.value)}
								className="h-10 bg-white/80 border-black/8 rounded-xl text-sm"
							/>
						</div>
						<div className="space-y-1.5">
							<Label className="text-xs text-muted-foreground flex items-center gap-1.5">
								<TagIcon className="h-3 w-3" /> Tag
							</Label>
							<Select value={transaction.tag || ''} onValueChange={v => updateField('tag', v)}>
								<SelectTrigger className="h-10 bg-white/80 border-black/8 rounded-xl text-sm">
									<SelectValue placeholder="Tag" />
								</SelectTrigger>
								<SelectContent>
									{tags.map(t => (
										<SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>
									))}
								</SelectContent>
							</Select>
						</div>
					</div>

					<div className="space-y-1.5">
						<Label className="text-xs text-muted-foreground flex items-center gap-1.5">
							<FolderOpen className="h-3 w-3" /> Category
						</Label>
						<Select value={transaction.category || ''} onValueChange={v => updateField('category', v)}>
							<SelectTrigger className="h-10 bg-white/80 border-black/8 rounded-xl text-sm">
								<SelectValue placeholder="Select category" />
							</SelectTrigger>
							<SelectContent>
								{categories.map(c => (
									<SelectItem key={c.id} value={c.id}>
										<span
											className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold text-white"
											style={{ backgroundColor: c.color || '#ababab' }}
										>
											{c.name}
										</span>
									</SelectItem>
								))}
							</SelectContent>
						</Select>
					</div>
				</div>

				{/* Actions */}
				<div className="px-5 pb-5 flex flex-col gap-2">
					<button
						onClick={handleOk}
						disabled={isDisabled}
						className="w-full h-11 rounded-xl font-semibold text-sm text-white transition-all duration-200 active:scale-[0.98] disabled:opacity-40 disabled:cursor-not-allowed shadow-lg"
						style={{
							backgroundColor: isDisabled ? '#9ca3af' : accentColor,
							boxShadow: isDisabled ? 'none' : `0 4px 14px ${accentColor}40`,
						}}
					>
						Create {type}
					</button>
					<button
						onClick={() => onOpenChange(false)}
						className="w-full h-9 rounded-xl text-sm text-muted-foreground hover:text-foreground transition-colors"
					>
						Cancel
					</button>
				</div>
			</DialogContent>
		</Dialog>
	);
}
