// src/components/Family/UpdateTransactionPopup.tsx
import { useState, useEffect, useMemo } from 'react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../ui/dialog';
import { clone, equals, openNotificationWithIcon, setIsLoading } from '../../services/utils';
import { DataBaseClient } from '../../api/db';
import { useCategoryStore } from '../../stores/category';
import { useTagStore } from '../../stores/tag';
import { useTransactionStore } from '../../stores/transaction';
import { Transaction } from '../../models/transaction';

interface Props {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	transaction: Transaction;
}

export default function UpdateTransactionPopup({ open, onOpenChange, transaction: propTransaction }: Props) {
	const [transaction, setTransaction] = useState<Transaction>(clone(propTransaction));
	const allCategories = useCategoryStore(s => s.categories);
	const tags = useTagStore(s => s.tags);
	const categories = useMemo(() => allCategories.filter(c => c.type === transaction.type), [allCategories, transaction.type]);

	useEffect(() => {
		setTransaction(clone(propTransaction));
	}, [propTransaction]);

	const updateField = (field: string, value: any) => {
		setTransaction(prev => ({ ...prev, [field]: value }));
	};

	const handleOk = () => {
		setIsLoading(true);
		DataBaseClient.Transaction.update(transaction)
			.then(() => {
				openNotificationWithIcon('success', 'Success', 'Transaction ' + transaction.description + ' updated');
				useTransactionStore.getState().updateTransaction(transaction);
				onOpenChange(false);
			})
			.catch(err => console.error(err))
			.finally(() => setIsLoading(false));
	};

	const isDisabled = !transaction.amount || !transaction.date || !transaction.description || !transaction.category || equals(transaction, propTransaction);

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>Update Transaction</DialogTitle>
				</DialogHeader>
				<div className="flex flex-col gap-3 items-start">
					<div className="w-full">
						<p className="text-sm mb-1">Date</p>
						<Input type="date" value={transaction.date} onChange={e => updateField('date', e.target.value)} />
					</div>
					<div className="w-full">
						<p className="text-sm mb-1">Description</p>
						<Input type="text" value={transaction.description} onChange={e => updateField('description', e.target.value)} placeholder="Enter a description" />
					</div>
					<div className="w-full">
						<p className="text-sm mb-1">Amount</p>
						<div className="flex items-center gap-2">
							<Input type="number" min={0} step={0.01} value={transaction.amount} onChange={e => updateField('amount', parseFloat(e.target.value) || 0)} placeholder="Enter an amount" />
							<span>€</span>
						</div>
					</div>
					<div className="w-full">
						<p className="text-sm mb-1">Category</p>
						<Select value={transaction.category} onValueChange={v => updateField('category', v)}>
							<SelectTrigger><SelectValue /></SelectTrigger>
							<SelectContent>
								{categories.map(c => (
									<SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>
								))}
							</SelectContent>
						</Select>
					</div>
					<div className="w-full">
						<p className="text-sm mb-1">Tag</p>
						<Select value={transaction.tag || ''} onValueChange={v => updateField('tag', v)}>
							<SelectTrigger><SelectValue /></SelectTrigger>
							<SelectContent>
								{tags.map(t => (
									<SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>
								))}
							</SelectContent>
						</Select>
					</div>
				</div>
				<DialogFooter>
					<Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
					<Button onClick={handleOk} disabled={isDisabled}>Update</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

// src/components/Family/UpdateTransactionPopup.vue
<template>
	<a-modal
		v-model:visible="visible"
		title="Update Transaction"
		@cancel="emits('close')"
		:loading="loading"
		:disabled="true"
	>
		<div class="input-form">
			<a-row>
				<p>Date</p>
				<a-input
					class="full-width"
					type="date"
					v-model:value="transaction.date"
					placeholder="Choose a date"
				></a-input>
			</a-row>
			<a-row>
				<p>Description</p>
				<a-input
					class="full-width"
					type="text"
					v-model:value="transaction.description"
					placeholder="Enter a description"
				></a-input>
			</a-row>
			<a-row>
				<p>Amount</p>
				<a-input-number
					class="full-width"
					v-model:value="transaction.amount"
					placeholder="Enter an amount"
					:min="0"
					:precision="2"
					addon-after="€"
				/>
			</a-row>
			<a-row class="full-width">
				<p>Category</p>
				<a-select class="full-width" ref="select" v-model:value="transaction.category">
					<a-select-option
						v-for="category in categories"
						:key="category.id"
						:value="category.id"
						>{{ category.name }}</a-select-option
					>
				</a-select>
			</a-row>
			<a-row class="full-width">
				<p>Tag</p>
				<a-select class="full-width" ref="select" v-model:value="transaction.tag">
					<a-select-option v-for="tag in tags" :key="tag.id" :value="tag.id">{{
						tag.name
					}}</a-select-option>
				</a-select>
			</a-row>
		</div>
		<template #footer>
			<a-button key="back" @click="emits('close')">Cancel</a-button>
			<a-button
				key="submit"
				type="primary"
				:loading="loading"
				@click="handleOk"
				:disabled="
					!transaction.amount ||
					!transaction.date ||
					!transaction.description ||
					!transaction.category ||
					equals(transaction, props.transaction)
				"
				>Update</a-button
			>
		</template>
	</a-modal>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { Transaction } from '../../models/transaction';
import {
	clone,
	equals,
	loading,
	openNotificationWithIcon,
	setIsLoading,
} from '../../services/utils';
import { DataBaseClient } from '../../api/db';
import { useCategoryStore } from '../../stores/category';
import { useTagStore } from '../../stores/tag';
import { useTransactionStore } from '../../stores/transaction';

const props = defineProps<{
	visible: boolean;
	transaction: Transaction;
}>();

const emits = defineEmits(['close']);

const visible = ref<boolean>(false);
const transaction = ref<Transaction>(clone(props.transaction));

watch(
	() => props.visible,
	() => (visible.value = props.visible)
);
watch(
	() => props.transaction,
	() => (transaction.value = clone(props.transaction))
);

watch(
	() => visible.value,
	() => {
		if (!visible.value) emits('close');
	}
);

const categories = computed(() =>
	useCategoryStore().categories.filter(c => c.type === transaction.value.type)
);
const tags = computed(() => useTagStore().tags);

const handleOk = () => {
	setIsLoading(true);
	DataBaseClient.Transaction.update(transaction.value)
		.then(() => {
			openNotificationWithIcon(
				'success',
				'Success',
				'Transaction ' + transaction.value.description + ' updated'
			);
			useTransactionStore().updateTransaction(transaction.value);
			emits('close');
		})
		.catch(err => console.error(err))
		.finally(() => setIsLoading(false));
};
</script>

<style lang="scss" scoped>
.input-form {
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	align-items: flex-start;
	gap: 0.75rem;
}
</style>
