// src/components/Family/YearStatsPopup.vue
<template>
	<a-modal
		v-model:visible="visible"
		:title="`Stats for ${props.year}`"
		@cancel="emits('close')"
		:disabled="true"
	>
		<a-row>
			<a-col :span="6">
				<a-statistic
					title="Balance"
					:value="totalSumEarnings + totalSumExpenses"
					:precision="0"
					suffix="€"
					:value-style="{
						color: totalSumEarnings > -totalSumExpenses ? '#3f8600' : '#cf1322',
					}"
				/>
			</a-col>
			<a-col :span="6">
				<a-statistic
					title="Tot Earnings"
					:value="totalSumEarnings"
					:precision="0"
					suffix="€"
					:value-style="{ color: '#3f8600' }"
				/>
			</a-col>
			<a-col :span="6">
				<a-statistic
					title="Tot Expenses"
					:value="totalSumExpenses"
					:precision="0"
					suffix="€"
					:value-style="{ color: '#cf1322' }"
				/>
			</a-col>
			<a-col :span="6">
				<a-statistic
					title="Saving Rate"
					:value="savingRate"
					:precision="2"
					suffix="%"
					:value-style="{
						color: savingRate ? '#3f8600' : '#cf1322',
					}"
				/>
			</a-col>
		</a-row>
		<a-tabs v-model:activeKey="activeKey" v-if="earnings.length || expenses.length">
			<a-tab-pane key="1" tab="Monthly Overview">
				<div style="height: 450px; width: 100%">
					<Bar :data="dataMonthly" :options="(options as any)" id="stats-monthly" />
				</div>
			</a-tab-pane>
			<a-tab-pane key="2" tab="Categories">
				<YearStatsCategories :expenses="expenses" :earnings="earnings" />
			</a-tab-pane>
		</a-tabs>
		<div v-else>
			<p>No data available for this year</p>
			<p>Would you like to freeze this year?</p>
			<a-button type="primary" @click="emits('freeze')">Freeze</a-button>
		</div>
		<template #footer>
			<a-button key="back" @click="emits('close')">Close</a-button>
			<a-button type="primary" key="enter" @click="emits('freeze')">{{
				expenses.length > 0 || earnings.length > 0 ? 'Update' : 'Freeze'
			}}</a-button>
		</template>
	</a-modal>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';

import {
	Chart as ChartJS,
	ArcElement,
	Tooltip,
	Legend,
	CategoryScale,
	LinearScale,
	BarElement,
} from 'chart.js';
import { Bar } from 'vue-chartjs';
import { IStats } from '../../models/stats';
import YearStatsCategories from './YearStatsCategories.vue';

ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement);

const props = defineProps<{
	visible: boolean;
	year: string;
	expenses: IStats[];
	earnings: IStats[];
}>();

const emits = defineEmits(['close', 'freeze']);

const activeKey = ref('1');

const visible = ref<boolean>(false);

const dataMonthly = computed(() => {
	const months = props.expenses
		.map(e => e.month)
		.sort((a, b) => {
			const aDate = new Date(`1 ${a}`);
			const bDate = new Date(`1 ${b}`);
			return aDate.getTime() - bDate.getTime();
		});

	const monthsEarnings = months.map(m => props.earnings.find(e => e.month === m)!);
	const monthsExpenses = months.map(m => props.expenses.find(e => e.month === m)!);
	const data = {
		labels: months,
		datasets: [
			{
				label: 'Expenses',
				backgroundColor: '#cf1322',
				data: monthsExpenses.map(e => e.total),
				// change color
				color: '#ababab',
			},
			{
				label: 'Earnings',
				backgroundColor: '#3f8600',
				data: monthsEarnings.map(e => e.total),
			},
		],
	};
	return data;
});

const totalSumExpenses = computed(
	() => -1 * props.expenses.reduce((acc, curr) => acc + curr.total, 0)
);
const totalSumEarnings = computed(() => props.earnings.reduce((acc, curr) => acc + curr.total, 0));

const savingRate = computed(
	() => (100 * (totalSumEarnings.value + totalSumExpenses.value)) / totalSumEarnings.value
);

watch(
	() => props.visible,
	() => (visible.value = props.visible)
);

watch(
	() => visible.value,
	() => {
		if (!visible.value) emits('close');
	}
);

const options = {
	responsive: true,
	maintainAspectRatio: false,
	plugins: {
		legend: {
			position: 'bottom',
		},
	},
};
</script>

<style lang="scss" scoped>
.input-form {
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	align-items: flex-start;
}
</style>

// src/components/Family/YearStatsPopup.tsx
import { useMemo } from 'react';
import { Button } from '../ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../ui/dialog';
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement } from 'chart.js';
import { Bar } from 'react-chartjs-2';
import { IStats } from '../../models/stats';
import YearStatsCategories from './YearStatsCategories';

ChartJS.register(ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement);

interface Props {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	year: string;
	expenses: IStats[];
	earnings: IStats[];
	onFreeze: () => void;
}

const options = {
	responsive: true,
	maintainAspectRatio: false,
	plugins: { legend: { position: 'bottom' as const } },
};

export default function YearStatsPopup({ open, onOpenChange, year, expenses, earnings, onFreeze }: Props) {
	const totalSumExpenses = useMemo(() => -1 * expenses.reduce((acc, curr) => acc + curr.total, 0), [expenses]);
	const totalSumEarnings = useMemo(() => earnings.reduce((acc, curr) => acc + curr.total, 0), [earnings]);
	const savingRate = useMemo(() => (100 * (totalSumEarnings + totalSumExpenses)) / totalSumEarnings, [totalSumEarnings, totalSumExpenses]);

	const dataMonthly = useMemo(() => {
		const months = expenses
			.map(e => e.month)
			.sort((a, b) => new Date(`1 ${a}`).getTime() - new Date(`1 ${b}`).getTime());
		return {
			labels: months,
			datasets: [
				{ label: 'Expenses', backgroundColor: '#cf1322', data: months.map(m => expenses.find(e => e.month === m)!.total) },
				{ label: 'Earnings', backgroundColor: '#3f8600', data: months.map(m => earnings.find(e => e.month === m)?.total || 0) },
			],
		};
	}, [expenses, earnings]);

	const balance = totalSumEarnings + totalSumExpenses;

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent className="max-w-lg">
				<DialogHeader>
					<DialogTitle>Stats for {year}</DialogTitle>
				</DialogHeader>
				<div className="grid grid-cols-4 gap-2 mb-4">
					<div className="flex flex-col">
						<span className="text-xs text-muted-foreground">Balance</span>
						<span className="text-lg font-semibold" style={{ color: balance >= 0 ? '#3f8600' : '#cf1322' }}>{Math.round(balance)} €</span>
					</div>
					<div className="flex flex-col">
						<span className="text-xs text-muted-foreground">Tot Earnings</span>
						<span className="text-lg font-semibold text-earning">{Math.round(totalSumEarnings)} €</span>
					</div>
					<div className="flex flex-col">
						<span className="text-xs text-muted-foreground">Tot Expenses</span>
						<span className="text-lg font-semibold text-expense">{Math.round(totalSumExpenses)} €</span>
					</div>
					<div className="flex flex-col">
						<span className="text-xs text-muted-foreground">Saving Rate</span>
						<span className="text-lg font-semibold" style={{ color: savingRate > 0 ? '#3f8600' : '#cf1322' }}>{savingRate ? savingRate.toFixed(2) : 0} %</span>
					</div>
				</div>
				{earnings.length || expenses.length ? (
					<Tabs defaultValue="1">
						<TabsList>
							<TabsTrigger value="1">Monthly Overview</TabsTrigger>
							<TabsTrigger value="2">Categories</TabsTrigger>
						</TabsList>
						<TabsContent value="1">
							<div className="h-[450px] w-full">
								<Bar data={dataMonthly} options={options} />
							</div>
						</TabsContent>
						<TabsContent value="2">
							<YearStatsCategories expenses={expenses} earnings={earnings} />
						</TabsContent>
					</Tabs>
				) : (
					<div className="text-center">
						<p>No data available for this year</p>
						<p>Would you like to freeze this year?</p>
						<Button onClick={onFreeze}>Freeze</Button>
					</div>
				)}
				<DialogFooter>
					<Button variant="outline" onClick={() => onOpenChange(false)}>Close</Button>
					<Button onClick={onFreeze}>{expenses.length > 0 || earnings.length > 0 ? 'Update' : 'Freeze'}</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
