// src/pages/Family.vue
<template>
	<Avatar :position="'topLeft'" />
	<h1>Family</h1>
	<ExportButtons />
	<a-tabs
		v-model:activeKey="activeYear"
		style="padding: 10px; height: calc(100vh - 100px); position: relative"
	>
		<a-tab-pane :key="year" :tab="year" v-for="year in YEARS">
			<a-tabs v-model:activeKey="activeMonth">
				<a-tab-pane :key="month" :tab="month" v-for="month in MONTHS">
					<MonthBalance :month="month" :year="year" />
				</a-tab-pane>
			</a-tabs>
		</a-tab-pane>
		<span class="stats-icon">
			<LineChartOutlined style="cursor: pointer" @click="openPopupForYearlyStats" />
		</span>
	</a-tabs>
	<div class="flex-center" style="justify-content: space-around">
		<a-button
			type="primary"
			danger
			@click="openPopupFor('expense')"
			style="background: #cf1322; border-color: #cf1322"
			><PlusOutlined /> Exp</a-button
		>
		<a-button
			type="primary"
			success
			@click="openPopupFor('earning')"
			style="background: #3f8600; border-color: #3f8600; margin-left: 5px"
			><PlusOutlined /> Earn</a-button
		>
	</div>
	<NewTransactionPopup
		:visible="newTransactionPopupIsVisibile"
		:type="type"
		@close="newTransactionPopupIsVisibile = false"
	/>
	<YearStatsPopup
		:year="activeYear"
		:earnings="yearlyEarnings"
		:expenses="yearlyExpenses"
		:visible="yearStatsPopupVisible"
		@close="yearStatsPopupVisible = false"
		@freeze="freezeYear"
	/>
	<SettingOutlined @click="sideMenuVisible = true" id="icon-open-settings" />
	<Settings :visible="sideMenuVisible" @close="sideMenuVisible = false" />
</template>

<script setup lang="ts">
import { LineChartOutlined, PlusOutlined, SettingOutlined } from '@ant-design/icons-vue/lib/icons';
import { ComputedRef, computed, ref } from 'vue';
import { DataBaseClient } from '../api/db';
import Avatar from '../components/Avatar.vue';
import ExportButtons from '../components/ExportButtons.vue';
import NewTransactionPopup from '../components/Family/NewTransactionPopup.vue';
import Settings from '../components/Family/Settings/Settings.vue';
import YearStatsPopup from '../components/Family/YearStatsPopup.vue';
import { IStats } from '../models/stats';
import { Transaction } from '../models/transaction';
import { MONTHS, YEARS, setIsLoading } from '../services/utils';
import { useCategoryStore } from '../stores/category';
import { useStatsStore } from '../stores/stats';
import { useTagStore } from '../stores/tag';

const activeMonth = ref(MONTHS[new Date().getMonth()]);
const activeYear = ref(new Date().getFullYear().toString());

const getCategories = async () => {
	setIsLoading(true);
	await DataBaseClient.Category.get().then(results => useCategoryStore().setCategories(results));
	setIsLoading(false);
};

const getTags = async () => {
	setIsLoading(true);
	await DataBaseClient.Tag.get().then(results => useTagStore().setTags(results));
	setIsLoading(false);
};

const categories = computed(() =>
	useCategoryStore().categories.filter(c => c.type === 'earning' || c.type === 'expense')
);

const includedCategoriesIds = computed(() =>
	categories.value.filter(c => !c.excludeFromBudget).map(c => c.id)
);

// *** add new transaction popup

const newTransactionPopupIsVisibile = ref(false);
const type = ref<'expense' | 'earning'>('earning');

const openPopupFor = (_type: 'expense' | 'earning') => {
	type.value = _type;
	newTransactionPopupIsVisibile.value = true;
};

// *** stats popup
const yearStatsPopupVisible = ref(false);
const yearlyEarnings: ComputedRef<IStats[]> = computed(() => {
	return useStatsStore().stats.filter(s => s.type === 'earning' && s.year === activeYear.value);
});
const yearlyExpenses: ComputedRef<IStats[]> = computed(() => {
	return useStatsStore().stats.filter(s => s.type === 'expense' && s.year === activeYear.value);
});
const openPopupForYearlyStats = async () => {
	yearStatsPopupVisible.value = true;
	setIsLoading(true);
	await DataBaseClient.Stats.getByYear(activeYear.value).then(results =>
		useStatsStore().setStats(results)
	);
	setIsLoading(false);
};

// *** freeze year

const getMonthSummaryByCategory = (transactions: Transaction[]) => {
	const categories = [...new Set(transactions.map(t => t.category))];
	const summary = categories.map(category => {
		const categoryTransactions = transactions.filter(t => t.category === category);
		const categoryTransactionsSum = categoryTransactions.reduce(
			(acc, curr) => acc + curr.amount,
			0
		);
		return {
			categoryId: category,
			total: categoryTransactionsSum,
		};
	});
	return summary;
};

const freezeYear = async () => {
	const year = activeYear.value;
	setIsLoading(true);
	try {
		// get transaction for all the year
		const yearTransactions: Transaction[] = await DataBaseClient.Transaction.get({
			year,
		});

		const yearStats: IStats[] = [];

		const months = [...new Set(yearTransactions.map(t => t.month))];

		months
			.sort((a, b) => {
				const aDate = new Date(`1 ${a}`);
				const bDate = new Date(`1 ${b}`);
				return aDate.getTime() - bDate.getTime();
			})
			.forEach(month => {
				const monthTransactions = yearTransactions
					.filter(t => t.month === month)
					.filter(t => includedCategoriesIds.value.includes(t.category));
				const monthEarnings = monthTransactions.filter(t => t.type === 'earning');
				const monthExpenses = monthTransactions.filter(t => t.type === 'expense');
				const monthEarningsSum = monthEarnings.reduce((acc, curr) => acc + curr.amount, 0);
				const monthExpensesSum = monthExpenses.reduce((acc, curr) => acc + curr.amount, 0);
				const monthEarningsSummary = getMonthSummaryByCategory(monthEarnings);
				const monthExpensesSummary = getMonthSummaryByCategory(monthExpenses);
				yearStats.push({
					month,
					year,
					type: 'earning',
					total: monthEarningsSum,
					categorySummary: monthEarningsSummary,
					lastUpdate: new Date().toDateString(),
				});
				yearStats.push({
					month,
					year,
					type: 'expense',
					categorySummary: monthExpensesSummary,
					total: monthExpensesSum,
					lastUpdate: new Date().toDateString(),
				});
			});
		if (useStatsStore().stats.length)
			await DataBaseClient.Stats.bulkDelete(useStatsStore().stats.map(s => s.id));
		await DataBaseClient.Stats.bulkAdd(yearStats);
		useStatsStore().reset();
	} catch (e) {
		console.log(e);
	} finally {
		setIsLoading(false);
	}
};

// *** side menu

const sideMenuVisible = ref<boolean>(false);

getCategories();
getTags();
</script>

<style scoped lang="scss">
#icon-open-settings {
	position: absolute;
	top: 10px;
	right: 10px;
	height: 25px;
	width: 25px;
}
.stats-icon {
	position: absolute;
	top: 20px;
	right: 10px;
	height: 25px;
	width: 25px;
	padding: 10px;
	display: flex;
	align-items: center;
}
</style>

// src/pages/Family.tsx
import { useState, useEffect, useMemo, useCallback } from 'react';
import { Settings, Plus, LineChart } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../components/ui/tabs';
import Avatar from '../components/Avatar';
import MonthBalance from '../components/Family/MonthBalance';
import NewTransactionPopup from '../components/Family/NewTransactionPopup';
import YearStatsPopup from '../components/Family/YearStatsPopup';
import SettingsPanel from '../components/Family/Settings/Settings';
import { MONTHS, YEARS, setIsLoading } from '../services/utils';
import { useCategoryStore } from '../stores/category';
import { useStatsStore } from '../stores/stats';
import { useTagStore } from '../stores/tag';
import { DataBaseClient } from '../api/db';
import { IStats } from '../models/stats';
import { Transaction } from '../models/transaction';

export default function Family() {
	const [activeMonth, setActiveMonth] = useState(MONTHS[new Date().getMonth()]);
	const [activeYear, setActiveYear] = useState(new Date().getFullYear().toString());
	const [newTransactionPopupVisible, setNewTransactionPopupVisible] = useState(false);
	const [type, setType] = useState<'expense' | 'earning'>('earning');
	const [yearStatsPopupVisible, setYearStatsPopupVisible] = useState(false);
	const [sideMenuVisible, setSideMenuVisible] = useState(false);

	const categories = useCategoryStore(s => s.categories);
	const stats = useStatsStore(s => s.stats);

	const includedCategoriesIds = useMemo(
		() =>
			categories
				.filter(c => (c.type === 'earning' || c.type === 'expense') && !c.excludeFromBudget)
				.map(c => c.id),
		[categories]
	);

	const yearlyEarnings = useMemo(
		() => stats.filter(s => s.type === 'earning' && s.year === activeYear),
		[stats, activeYear]
	);
	const yearlyExpenses = useMemo(
		() => stats.filter(s => s.type === 'expense' && s.year === activeYear),
		[stats, activeYear]
	);

	useEffect(() => {
		const load = async () => {
			setIsLoading(true);
			const [cats, tags] = await Promise.all([
				DataBaseClient.Category.get(),
				DataBaseClient.Tag.get(),
			]);
			useCategoryStore.getState().setCategories(cats);
			useTagStore.getState().setTags(tags);
			setIsLoading(false);
		};
		load();
	}, []);

	const openPopupFor = (t: 'expense' | 'earning') => {
		setType(t);
		setNewTransactionPopupVisible(true);
	};

	const openPopupForYearlyStats = async () => {
		setYearStatsPopupVisible(true);
		setIsLoading(true);
		const results = await DataBaseClient.Stats.getByYear(activeYear);
		useStatsStore.getState().setStats(results);
		setIsLoading(false);
	};

	const getMonthSummaryByCategory = (transactions: Transaction[]) => {
		const cats = [...new Set(transactions.map(t => t.category))];
		return cats.map(category => {
			const catTransactions = transactions.filter(t => t.category === category);
			const total = catTransactions.reduce((acc, curr) => acc + curr.amount, 0);
			return { categoryId: category, total };
		});
	};

	const freezeYear = useCallback(async () => {
		setIsLoading(true);
		try {
			const yearTransactions: Transaction[] = await DataBaseClient.Transaction.get({
				year: activeYear,
			});
			const yearStats: IStats[] = [];
			const months = [...new Set(yearTransactions.map(t => t.month))];
			months
				.sort((a, b) => new Date(`1 ${a}`).getTime() - new Date(`1 ${b}`).getTime())
				.forEach(month => {
					const monthTransactions = yearTransactions
						.filter(t => t.month === month)
						.filter(t => includedCategoriesIds.includes(t.category));
					const monthEarnings = monthTransactions.filter(t => t.type === 'earning');
					const monthExpenses = monthTransactions.filter(t => t.type === 'expense');
					const monthEarningsSum = monthEarnings.reduce((acc, curr) => acc + curr.amount, 0);
					const monthExpensesSum = monthExpenses.reduce((acc, curr) => acc + curr.amount, 0);
					yearStats.push({
						month,
						year: activeYear,
						type: 'earning',
						total: monthEarningsSum,
						categorySummary: getMonthSummaryByCategory(monthEarnings),
						lastUpdate: new Date().toDateString(),
					});
					yearStats.push({
						month,
						year: activeYear,
						type: 'expense',
						total: monthExpensesSum,
						categorySummary: getMonthSummaryByCategory(monthExpenses),
						lastUpdate: new Date().toDateString(),
					});
				});
			const currentStats = useStatsStore.getState().stats;
			if (currentStats.length)
				await DataBaseClient.Stats.bulkDelete(currentStats.map(s => s.id));
			await DataBaseClient.Stats.bulkAdd(yearStats);
			useStatsStore.getState().reset();
		} catch (e) {
			console.log(e);
		} finally {
			setIsLoading(false);
		}
	}, [activeYear, includedCategoriesIds]);

	return (
		<div className="relative">
			<Avatar position="topLeft" />
			<h1 className="text-2xl font-bold">Family</h1>
			<Tabs value={activeYear} onValueChange={setActiveYear} className="p-2.5 h-[calc(100vh-100px)] relative">
				<TabsList className="flex-wrap h-auto">
					{YEARS.map(year => (
						<TabsTrigger key={year} value={year}>{year}</TabsTrigger>
					))}
				</TabsList>
				{YEARS.map(year => (
					<TabsContent key={year} value={year}>
						<Tabs value={activeMonth} onValueChange={setActiveMonth}>
							<TabsList className="flex-wrap h-auto">
								{MONTHS.map(month => (
									<TabsTrigger key={month} value={month}>{month.substring(0, 3)}</TabsTrigger>
								))}
							</TabsList>
							{MONTHS.map(month => (
								<TabsContent key={month} value={month}>
									<MonthBalance month={month} year={year} />
								</TabsContent>
							))}
						</Tabs>
					</TabsContent>
				))}
				<span className="absolute top-5 right-2.5 flex items-center p-2.5 cursor-pointer" onClick={openPopupForYearlyStats}>
					<LineChart className="h-5 w-5" />
				</span>
			</Tabs>
			<div className="flex items-center justify-around">
				<Button
					onClick={() => openPopupFor('expense')}
					className="bg-expense hover:bg-expense/90"
				>
					<Plus className="mr-1 h-4 w-4" /> Exp
				</Button>
				<Button
					onClick={() => openPopupFor('earning')}
					className="bg-earning hover:bg-earning/90 ml-1"
				>
					<Plus className="mr-1 h-4 w-4" /> Earn
				</Button>
			</div>
			<NewTransactionPopup
				open={newTransactionPopupVisible}
				onOpenChange={setNewTransactionPopupVisible}
				type={type}
			/>
			<YearStatsPopup
				open={yearStatsPopupVisible}
				onOpenChange={setYearStatsPopupVisible}
				year={activeYear}
				earnings={yearlyEarnings}
				expenses={yearlyExpenses}
				onFreeze={freezeYear}
			/>
			<Settings
				className="absolute top-2.5 right-2.5 h-6 w-6 cursor-pointer"
				onClick={() => setSideMenuVisible(true)}
			/>
			<SettingsPanel open={sideMenuVisible} onOpenChange={setSideMenuVisible} />
		</div>
	);
}
