// src/pages/Todo.tsx
import { useState, useEffect, useMemo } from 'react';
import { Plus, X } from 'lucide-react';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Checkbox } from '../components/ui/checkbox';
import { Separator } from '../components/ui/separator';
import Avatar from '../components/Avatar';
import { DataBaseClient } from '../api/db';
import { Todo as TodoModel } from '../models/todo';

export default function Todo() {
	const [items, setItems] = useState<TodoModel[]>([]);
	const [newItem, setNewItem] = useState('');

	useEffect(() => {
		let unsubscribe: (() => void) | undefined;
		DataBaseClient.Todo.getRT((todos: TodoModel[]) => {
			setItems(todos);
		}).then(unsub => {
			unsubscribe = unsub;
		});
		return () => {
			unsubscribe?.();
		};
	}, []);

	const sortedItems = useMemo(() => {
		return [...items].sort((i1, i2) => {
			const c1 = i1.checked ? 1 : -1;
			const c2 = i2.checked ? 1 : -1;
			const diff = c1 - c2;
			if (!diff) return i1.label.localeCompare(i2.label);
			return c1 - c2;
		});
	}, [items]);

	const addNewItem = () => {
		if (newItem) {
			DataBaseClient.Todo.create({ label: newItem, checked: false }).then(() => {
				setNewItem('');
			});
		}
	};

	const onCheck = (item: TodoModel) => {
		DataBaseClient.Todo.update({ ...item, checked: !item.checked });
	};

	const deleteItem = (item: TodoModel) => {
		DataBaseClient.Todo.delete(item.id);
	};

	return (
		<>
			<Avatar position="topLeft" />
			<h1 className="text-2xl font-bold">Home Todo List</h1>
			<p>Here is a list of things to do</p>
			<div className="flex px-4">
				<Input
					value={newItem}
					onChange={e => setNewItem(e.target.value)}
					placeholder="Add new"
					onKeyDown={e => e.key === 'Enter' && addNewItem()}
				/>
				<Button onClick={addNewItem} disabled={!newItem}>
					Add <Plus className="ml-1 h-4 w-4" />
				</Button>
			</div>
			<Separator className="my-4" />
			<div className="px-4 flex flex-col gap-2 items-start max-h-[calc(100vh-200px)] overflow-y-auto">
				{sortedItems.map(item => (
					<div key={item.id} className="flex justify-between items-center w-full">
						<div className="flex items-center gap-2">
							<Checkbox
								checked={item.checked}
								onCheckedChange={() => onCheck(item)}
							/>
							<span className={item.checked ? 'line-through' : ''}>
								{item.label}
							</span>
						</div>
						<X className="h-4 w-4 cursor-pointer" onClick={() => deleteItem(item)} />
					</div>
				))}
			</div>
		</>
	);
}

// src/pages/Todo.vue
<template>
	<Avatar :position="'topLeft'" />
	<h1>Home Todo List</h1>
	<p>Here is a list of things to do</p>
	<div style="display: flex; padding: 0 1rem">
		<a-input v-model:value="newItem" placeholder="Add new" />
		<a-button type="primary" @click="addNewItem" :disabled="!newItem" :loading="loading"
			>Add <PlusOutlined
		/></a-button>
	</div>
	<a-divider />
	<div
		style="
			padding: 1rem;
			display: flex;
			flex-direction: column;
			gap: 0.5rem;
			align-items: flex-start;
			max-height: calc(100vh - 200px);
			overflow-y: auto;
		"
	>
		<div
			v-for="(item, i) in sortedItems"
			:key="i"
			style="display: flex; justify-content: space-between; align-items: center; width: 100%"
		>
			<a-checkbox
				v-model:checked="item.checked"
				@change="onCheck(item)"
				:class="{ checked: item.checked }"
			>
				{{ item.label }}
			</a-checkbox>
			<CloseOutlined @click="deleteItem(item)" />
		</div>
	</div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import Avatar from '../components/Avatar.vue';
import { loading } from '../services/utils';
import { PlusOutlined, CloseOutlined } from '@ant-design/icons-vue';
import { DataBaseClient } from '../api/db';
import { Todo } from '../models/todo';

const items = ref<Todo[]>([]);

const sortedItems = computed(() => {
	return items.value.sort((i1, i2) => {
		const c1 = i1.checked ? 1 : -1;
		const c2 = i2.checked ? 1 : -1;
		const diff = c1 - c2;
		if (!diff) return i1.label.localeCompare(i2.label);
		return c1 - c2;
	});
});

const newItem = ref('');

const addNewItem = () => {
	if (newItem.value)
		DataBaseClient.Todo.create({
			label: newItem.value,
			checked: false,
		}).then(() => {
			newItem.value = '';
		});
};

DataBaseClient.Todo.getRT((todos: Todo[]) => {
	items.value = todos;
});

const onCheck = (item: Todo) => {
	DataBaseClient.Todo.update({ ...item, checked: item.checked });
};

const deleteItem = (item: Todo) => {
	DataBaseClient.Todo.delete(item.id);
};
</script>

<style scoped lang="scss">
.checked {
	text-decoration: line-through;
}
</style>
