// src/components/TransactionItem.vue
<template>
	<div
		style="
			position: relative;
			width: 100%;
			padding-right: 5px;
			display: flex;
			flex-direction: column;
			gap: 0.5rem;
		"
	>
		<a-row style="width: 100%">
			<a-col :span="16" class="ellipsis" style="text-transform: capitalize">
				<a-typography-text strong>
					{{ item.description }}
				</a-typography-text>
			</a-col>
			<a-col :span="8" class="right" style="display: flex; justify-content: flex-end">
				<div v-if="true || getCategory(item.category)?.excludeFromBudget">
					<a-tag :color="'gray'">E</a-tag>
				</div>
				<a-typography-text keyboard>{{ item.amount }} €</a-typography-text>
			</a-col>
		</a-row>
		<a-row style="width: 100%">
			<a-col :span="5" class="left">
				<a-typography-text code
					>{{ formatDate(item.date, true) }}
					<CalendarOutlined />
				</a-typography-text>
			</a-col>
			<a-col :span="13" class="left">
				<Category
					:category="getCategory(item.category)!"
					v-if="getCategory(item.category)"
				/>
			</a-col>
			<a-col :span="4" class="left">
				<Tag
					:tag="getTag(item.tag)!"
					v-if="getTag(item.tag) && item.tag !== 'XB0kK9DnZIIEsPKsaWEB'"
				/>
			</a-col>
			<a-col :span="2" class="center">
				<a-popconfirm
					@click.stop=""
					title="Are you sure delete this transaction?"
					ok-text="Yes"
					placement="left"
					cancel-text="No"
					@confirm="deleteTransaction(item)"
				>
					<DeleteOutlined />
				</a-popconfirm>
			</a-col>
		</a-row>
	</div>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import { DataBaseClient } from '../api/db';
import { Transaction } from '../models/transaction';
import { formatDate, openNotificationWithIcon } from '../services/utils';
import { useTransactionStore } from '../stores/transaction';
import { useCategoryStore } from '../stores/category';
import { useTagStore } from '../stores/tag';
import { DeleteOutlined, CalendarOutlined } from '@ant-design/icons-vue/lib/icons';
import Category from './Badges/Category.vue';
import Tag from './Badges/Tag.vue';

const props = defineProps<{
	item: Transaction;
}>();

const item = props.item;

const deleteTransaction = (transaction: Transaction) => {
	DataBaseClient.Transaction.delete(transaction.id)
		.then(() => {
			openNotificationWithIcon(
				'success',
				'Success',
				'Deleted transaction with id: ' + transaction.id
			);
			useTransactionStore().removeTransaction(transaction);
		})
		.catch(err => {
			console.error(err);
			openNotificationWithIcon(
				'error',
				'Error',
				'Failed deleting transaction with id:' + transaction.id
			);
		});
};

const categories = computed(() =>
	useCategoryStore().categories.filter(c => c.type === 'earning' || c.type === 'expense')
);
const tags = computed(() => useTagStore().tags);

const getCategory = (categoryId: string) => categories.value.find(c => c.id === categoryId);
const getTag = (tagId?: string) => tags.value.find(t => t.id === tagId);
</script>

// src/components/TransactionItem.tsx
import { Trash2, Calendar } from 'lucide-react';
import { Badge } from './ui/badge';
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from './ui/alert-dialog';
import CategoryBadge from './Badges/CategoryBadge';
import TagBadge from './Badges/TagBadge';
import { Transaction } from '../models/transaction';
import { formatDate, openNotificationWithIcon } from '../services/utils';
import { useTransactionStore } from '../stores/transaction';
import { useCategoryStore } from '../stores/category';
import { useTagStore } from '../stores/tag';
import { DataBaseClient } from '../api/db';

interface Props {
	item: Transaction;
}

export default function TransactionItem({ item }: Props) {
	const categories = useCategoryStore(s => s.categories);
	const tags = useTagStore(s => s.tags);
	const removeTransaction = useTransactionStore(s => s.removeTransaction);

	const getCategory = (categoryId: string) => categories.find(c => c.id === categoryId);
	const getTag = (tagId?: string) => tags.find(t => t.id === tagId);

	const deleteTransaction = (e: React.MouseEvent) => {
		e.stopPropagation();
		DataBaseClient.Transaction.delete(item.id)
			.then(() => {
				openNotificationWithIcon('success', 'Success', 'Deleted transaction with id: ' + item.id);
				removeTransaction(item);
			})
			.catch(err => {
				console.error(err);
				openNotificationWithIcon('error', 'Error', 'Failed deleting transaction with id:' + item.id);
			});
	};

	const category = getCategory(item.category);
	const tag = getTag(item.tag);

	return (
		<div className="relative w-full pr-[5px] flex flex-col gap-2">
			<div className="flex w-full">
				<div className="w-2/3 text-left truncate capitalize flex items-center gap-1">
					<strong>{item.description}</strong>
				</div>
				<div className="w-1/3 text-right flex justify-end items-center gap-1">
					{category?.excludeFromBudget && (
						<Badge variant="secondary" className="text-xs">E</Badge>
					)}
					<span className="bg-muted px-1.5 py-0.5 rounded text-sm font-mono">{item.amount} €</span>
				</div>
			</div>
			<div className="flex w-full items-center">
				<div className="w-1/5 text-left">
					<span className="bg-muted px-1 py-0.5 rounded text-xs font-mono">
						{formatDate(item.date, true)} <Calendar className="inline h-3 w-3" />
					</span>
				</div>
				<div className="w-[54%] text-left">
					{category && <CategoryBadge category={category} />}
				</div>
				<div className="w-[17%] text-left">
					{tag && item.tag !== 'XB0kK9DnZIIEsPKsaWEB' && <TagBadge tag={tag} />}
				</div>
				<div className="w-[8%] text-center" onClick={e => e.stopPropagation()}>
					<AlertDialog>
						<AlertDialogTrigger asChild>
							<Trash2 className="h-4 w-4 cursor-pointer text-muted-foreground hover:text-destructive" />
						</AlertDialogTrigger>
						<AlertDialogContent>
							<AlertDialogHeader>
								<AlertDialogTitle>Are you sure delete this transaction?</AlertDialogTitle>
							</AlertDialogHeader>
							<AlertDialogFooter>
								<AlertDialogCancel>No</AlertDialogCancel>
								<AlertDialogAction onClick={deleteTransaction}>Yes</AlertDialogAction>
							</AlertDialogFooter>
						</AlertDialogContent>
					</AlertDialog>
				</div>
			</div>
		</div>
	);
}
