// src/components/Family/Settings/CategoriesSettings.tsx
import { useState } from "react";
import type { Category } from "../../../models/category";
import { useCategoryStore } from "../../../stores/category";
import CategoryBadge from "../../Badges/CategoryBadge";
import { Button } from "../../ui/button";
import { Separator } from "../../ui/separator";
import NewCategoryPopup from "./NewCategoryPopup";
import UpdateCategoryPopup from "./UpdateCategoryPopup";

export default function CategoriesSettings() {
	const [newCategoryPopupVisible, setNewCategoryPopupVisible] = useState(false);
	const [updateCategoryPopupVisible, setUpdateCategoryPopupVisible] =
		useState(false);
	const [selectedCategory, setSelectedCategory] = useState<
		Category | undefined
	>();
	const categories = useCategoryStore((s) => s.categories);

	const onCategorySelected = (category: Category) => {
		setSelectedCategory(category);
		setUpdateCategoryPopupVisible(true);
	};

	return (
		<div className="text-left">
			<h4 className="font-semibold mb-2">Categories</h4>
			<Button onClick={() => setNewCategoryPopupVisible(true)}>Add New</Button>
			<NewCategoryPopup
				open={newCategoryPopupVisible}
				onOpenChange={setNewCategoryPopupVisible}
			/>
			<Separator className="my-4" />
			{selectedCategory && (
				<UpdateCategoryPopup
					open={updateCategoryPopupVisible}
					onOpenChange={setUpdateCategoryPopupVisible}
					category={selectedCategory}
				/>
			)}
			<p className="font-medium">Expenses</p>
			<div className="inline-flex flex-wrap gap-2.5 max-h-[300px] overflow-auto">
				{categories
					.filter((c) => c.type === "expense")
					.map((category) => (
						<div key={category.id} onClick={() => onCategorySelected(category)}>
							<CategoryBadge category={category} removable />
						</div>
					))}
			</div>
			<Separator className="my-4" />
			<p className="font-medium">Earnings</p>
			<div className="inline-flex flex-wrap gap-2.5 max-h-[300px] overflow-auto">
				{categories
					.filter((c) => c.type === "earning")
					.map((category) => (
						<div key={category.id} onClick={() => onCategorySelected(category)}>
							<CategoryBadge category={category} removable />
						</div>
					))}
			</div>
			<Separator className="my-4" />
		</div>
	);
}

// src/components/Family/Settings/CategoriesSettings.vue
<template>
	<h4>Categories</h4>
	<a-button type="primary" @click="newCategoryPopupIsVisibile = true"> Add New </a-button>
	<NewCategoryPopup
		:visible="newCategoryPopupIsVisibile"
		@close="newCategoryPopupIsVisibile = false"
	/>
	<a-divider />
	<UpdateCategoryPopup
		:visible="updateCategoryPopupIsVisibile"
		:category="selectedCategory"
		@close="updateCategoryPopupIsVisibile = false"
	/>
	<p>Expenses</p>
	<div class="flex-gap" style="max-height: 300px; overflow: auto">
		<CategoryBadge
			:removable="true"
			:category="category"
			@click="onCategorySelected(category)"
			v-for="category in categories.filter(c => c.type == 'expense')"
		/>
	</div>
	<a-divider />
	<p>Earnings</p>
	<div class="flex-gap" style="max-height: 300px; overflow: auto">
		<CategoryBadge
			:removable="true"
			:category="category"
			@click="onCategorySelected(category)"
			v-for="category in categories.filter(c => c.type == 'earning')"
		/>
	</div>
	<a-divider />
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { Category } from '../../../models/category';
import { useCategoryStore } from '../../../stores/category';
import NewCategoryPopup from './NewCategoryPopup.vue';
import CategoryBadge from '../../Badges/Category.vue';
import UpdateCategoryPopup from './UpdateCategoryPopup.vue';

const newCategoryPopupIsVisibile = ref(false);

const categories = computed(() => useCategoryStore().categories);

const updateCategoryPopupIsVisibile = ref(false);
const selectedCategory = ref<Category>();
const onCategorySelected = (category: Category) => {
	selectedCategory.value = category;
	updateCategoryPopupIsVisibile.value = true;
};
</script>
