// src/components/Family/Settings/NewCategoryPopup.tsx
import { useState } from 'react';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { Checkbox } from '../../ui/checkbox';
import { RadioGroup, RadioGroupItem } from '../../ui/radio-group';
import { Label } from '../../ui/label';
import { Badge } from '../../ui/badge';
import { Separator } from '../../ui/separator';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../ui/dialog';
import { openNotificationWithIcon, setIsLoading } from '../../../services/utils';
import { DataBaseClient } from '../../../api/db';
import { useCategoryStore } from '../../../stores/category';
import { ICategory } from '../../../models/category';

interface Props { open: boolean; onOpenChange: (open: boolean) => void; }

export default function NewCategoryPopup({ open, onOpenChange }: Props) {
	const newCategory = (): ICategory => ({ name: '', type: 'expense', description: undefined, color: '#ababab' });
	const [category, setCategory] = useState<ICategory>(newCategory());

	const updateField = (field: string, value: any) => setCategory(prev => ({ ...prev, [field]: value }));

	const handleOk = () => {
		setIsLoading(true);
		DataBaseClient.Category.create(category)
			.then(cat => {
				openNotificationWithIcon('success', 'Success', 'Category ' + cat.name + ' created');
				useCategoryStore.getState().addCategory(cat);
				setCategory(newCategory());
				onOpenChange(false);
			})
			.catch(err => console.error(err))
			.finally(() => setIsLoading(false));
	};

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent>
				<DialogHeader><DialogTitle>New Category</DialogTitle></DialogHeader>
				<div className="flex flex-col gap-3 items-start">
					<div className="w-full">
						<p className="text-sm mb-1">Name</p>
						<Input type="text" value={category.name} onChange={e => updateField('name', e.target.value)} placeholder="Category name" />
					</div>
					<div className="w-full">
						<p className="text-sm mb-1">Description</p>
						<Input type="text" value={category.description || ''} onChange={e => updateField('description', e.target.value)} placeholder="Optional description" />
					</div>
					<div className="flex items-center gap-4 w-full">
						<div>
							<p className="text-sm mb-1">Color</p>
							<input type="color" value={category.color || '#ababab'} onChange={e => updateField('color', e.target.value)} className="h-10 w-10 cursor-pointer" />
						</div>
						<div>
							<p className="text-sm mb-1">Type</p>
							<RadioGroup value={category.type} onValueChange={v => updateField('type', v)} className="flex gap-2">
								<div className="flex items-center gap-1"><RadioGroupItem value="expense" id="expense" /><Label htmlFor="expense">Expense</Label></div>
								<div className="flex items-center gap-1"><RadioGroupItem value="earning" id="earning" /><Label htmlFor="earning">Earning</Label></div>
							</RadioGroup>
						</div>
					</div>
					<div className="flex items-center gap-2">
						<Checkbox checked={!!category.excludeFromBudget} onCheckedChange={v => updateField('excludeFromBudget', v)} />
						<span className="text-sm">Exclude From Budget</span>
					</div>
				</div>
				{category.name && (
					<>
						<Separator />
						<div className="flex items-center justify-around">
							<p className="text-sm">Preview</p>
							<Badge style={{ backgroundColor: category.color, color: 'white' }}>{category.name}</Badge>
						</div>
					</>
				)}
				<DialogFooter>
					<Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
					<Button onClick={handleOk} disabled={!category.name}>Create</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

// src/components/Family/Settings/NewCategoryPopup.vue
<template>
	<a-modal
		v-model:visible="visible"
		title="New Category"
		@cancel="emits('close')"
		:loading="loading"
		:disabled="true"
	>
		<div class="input-form center">
			<a-row class="full-width" style="margin-top: 10px">
				<p>Name</p>
				<a-input
					class="full-width"
					type="text"
					v-model:value="category.name"
					placeholder="Category name"
				/>
			</a-row>
			<a-row class="full-width" style="margin-top: 10px">
				<p>Description</p>
				<a-input
					name="description"
					class="full-width"
					type="text"
					v-model:value="category.description"
					placeholder="Optional description"
				/>
			</a-row>
			<a-row class="full-width flex-center" style="margin-top: 10px">
				<a-col :span="10">
					<p>Color</p>
					<a-input
						name="color"
						type="color"
						v-model:value="category.color"
						placeholder="Background color"
					></a-input>
				</a-col>
				<a-col :span="14">
					<p>Type</p>
					<a-radio-group v-model:value="category.type">
						<a-radio-button value="expense">Expense</a-radio-button>
						<a-radio-button value="earning">Earning</a-radio-button>
					</a-radio-group>
				</a-col>
			</a-row>
			<a-row class="full-width" style="margin-top: 20px">
				<a-col :span="24">
					<a-checkbox v-model:checked="category.excludeFromBudget"
						>Exclude From Budget</a-checkbox
					>
				</a-col>
			</a-row>
		</div>
		<a-divider></a-divider>
		<div class="category-preview flex-center" v-if="category.name">
			<p>Preview</p>
			<a-tooltip>
				<template #title v-if="category.description">{{ category.description }}</template>
				<a-tag :color="category.color" size="large">{{ category.name }}</a-tag>
			</a-tooltip>
		</div>
		<template #footer>
			<a-button key="back" @click="emits('close')">Cancel</a-button>
			<a-button
				key="submit"
				type="primary"
				:loading="loading"
				@click="handleOk"
				:disabled="!category.name"
				>Create</a-button
			>
		</template>
	</a-modal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { ICategory } from '../../../models/category';
import { loading, openNotificationWithIcon, setIsLoading } from '../../../services/utils';
import { DataBaseClient } from '../../../api/db';
import { useCategoryStore } from '../../../stores/category';

const props = defineProps<{
	visible: boolean;
}>();

const emits = defineEmits(['close', 'ok']);

const visible = ref<boolean>(false);
const newCategory = (): ICategory => ({
	name: '',
	type: 'expense',
	description: undefined,
	color: '#ababab',
});
const category = ref<ICategory>(newCategory());
const resetCategory = () => (category.value = newCategory());

watch(
	() => props.visible,
	() => (visible.value = props.visible)
);

watch(
	() => visible.value,
	() => {
		if (!visible.value) emits('close');
	}
);

const handleOk = () => {
	setIsLoading(true);
	DataBaseClient.Category.create(category.value)
		.then(category => {
			openNotificationWithIcon(
				'success',
				'Success',
				'Category ' + category.name + ' created'
			);
			useCategoryStore().addCategory(category);
			resetCategory();
			emits('close');
		})
		.catch(err => console.error(err))
		.finally(() => setIsLoading(false));
};
</script>

<style lang="scss" scoped>
.input-form {
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	align-items: flex-start;
}
.category-preview {
	justify-content: space-around;
	p {
		margin-bottom: 0;
	}
}
</style>
