// src/components/Family/Settings/NewTagPopup.tsx
import { useState } from 'react';
import { Button } from '../../ui/button';
import { Input } from '../../ui/input';
import { Badge } from '../../ui/badge';
import { Separator } from '../../ui/separator';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '../../ui/dialog';
import { openNotificationWithIcon, setIsLoading } from '../../../services/utils';
import { DataBaseClient } from '../../../api/db';
import { useTagStore } from '../../../stores/tag';
import { ITag } from '../../../models/tag';

interface Props { open: boolean; onOpenChange: (open: boolean) => void; }

export default function NewTagPopup({ open, onOpenChange }: Props) {
	const newTag = (): ITag => ({ name: '', description: undefined, color: '#ababab' });
	const [tag, setTag] = useState<ITag>(newTag());
	const updateField = (field: string, value: any) => setTag(prev => ({ ...prev, [field]: value }));

	const handleOk = () => {
		setIsLoading(true);
		DataBaseClient.Tag.create(tag)
			.then(t => {
				openNotificationWithIcon('success', 'Success', 'Tag ' + t.name + ' created');
				useTagStore.getState().addTag(t);
				setTag(newTag());
				onOpenChange(false);
			})
			.catch(err => console.error(err))
			.finally(() => setIsLoading(false));
	};

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent>
				<DialogHeader><DialogTitle>New Tag</DialogTitle></DialogHeader>
				<div className="flex flex-col gap-3 items-start">
					<div className="w-full">
						<p className="text-sm mb-1">Name</p>
						<Input type="text" value={tag.name} onChange={e => updateField('name', e.target.value)} placeholder="Ex. ABC23" maxLength={5} />
					</div>
					<div className="w-full">
						<p className="text-sm mb-1">Description</p>
						<Input type="text" value={tag.description || ''} onChange={e => updateField('description', e.target.value)} placeholder="Optional description" />
					</div>
					<div>
						<p className="text-sm mb-1">Color</p>
						<input type="color" value={tag.color || '#ababab'} onChange={e => updateField('color', e.target.value)} className="h-10 w-10 cursor-pointer" />
					</div>
				</div>
				{tag.name && (
					<>
						<Separator />
						<div className="flex items-center justify-around">
							<p className="text-sm">Preview</p>
							<Badge style={{ backgroundColor: tag.color, color: 'white' }}>{tag.name}</Badge>
						</div>
					</>
				)}
				<DialogFooter>
					<Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
					<Button onClick={handleOk} disabled={!tag.name}>Create</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

// src/components/Family/Settings/NewTagPopup.vue
<template>
	<a-modal
		v-model:visible="visible"
		title="New Tag"
		@cancel="emits('close')"
		:loading="loading"
		:disabled="true"
	>
		<div class="input-form center">
			<a-row class="full-width" style="margin-top: 10px">
				<p>Name</p>
				<a-input
					class="full-width"
					type="text"
					v-model:value="tag.name"
					placeholder="Ex. ABC23"
					:maxlength="5"
				/>
			</a-row>
			<a-row class="full-width" style="margin-top: 10px">
				<p>Description</p>
				<a-input
					name="description"
					class="full-width"
					type="text"
					v-model:value="tag.description"
					placeholder="Optional description"
				/>
			</a-row>
			<a-row class="full-width flex-center" style="margin-top: 10px">
				<a-col :span="10">
					<p>Color</p>
					<a-input
						name="color"
						type="color"
						v-model:value="tag.color"
						placeholder="Background color"
					></a-input>
				</a-col>
			</a-row>
		</div>
		<a-divider></a-divider>
		<div class="tag-preview flex-center" v-if="tag.name">
			<p>Preview</p>
			<a-tooltip>
				<template #title v-if="tag.description">{{ tag.description }}</template>
				<a-tag :color="tag.color" size="large">{{ tag.name }}</a-tag>
			</a-tooltip>
		</div>
		<template #footer>
			<a-button key="back" @click="emits('close')">Cancel</a-button>
			<a-button
				key="submit"
				type="primary"
				:loading="loading"
				@click="handleOk"
				:disabled="!tag.name"
				>Create</a-button
			>
		</template>
	</a-modal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { ITag } from '../../../models/tag';
import { loading, openNotificationWithIcon, setIsLoading } from '../../../services/utils';
import { DataBaseClient } from '../../../api/db';
import { useTagStore } from '../../../stores/tag';

const props = defineProps<{
	visible: boolean;
}>();

const emits = defineEmits(['close', 'ok']);

const visible = ref<boolean>(false);
const newTag = (): ITag => ({
	name: '',
	description: undefined,
	color: '#ababab',
});
const tag = ref<ITag>(newTag());
const resetTag = () => (tag.value = newTag());

watch(
	() => props.visible,
	() => (visible.value = props.visible)
);

watch(
	() => visible.value,
	() => {
		if (!visible.value) emits('close');
	}
);

const handleOk = () => {
	setIsLoading(true);
	DataBaseClient.Tag.create(tag.value)
		.then(tag => {
			openNotificationWithIcon('success', 'Success', 'Tag ' + tag.name + ' created');
			useTagStore().addTag(tag);
			resetTag();
			emits('close');
		})
		.catch(err => console.error(err))
		.finally(() => setIsLoading(false));
};
</script>

<style lang="scss" scoped>
.input-form {
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	align-items: flex-start;
}
.tag-preview {
	justify-content: space-around;
	p {
		margin-bottom: 0;
	}
}
</style>
