// src/components/Family/Settings/TagsSettings.tsx
import { useState } from 'react';
import { Button } from '../../ui/button';
import { Separator } from '../../ui/separator';
import TagBadge from '../../Badges/TagBadge';
import NewTagPopup from './NewTagPopup';
import UpdateTagPopup from './UpdateTagPopup';
import { useTagStore } from '../../../stores/tag';
import { Tag } from '../../../models/tag';

export default function TagsSettings() {
	const [newTagPopupVisible, setNewTagPopupVisible] = useState(false);
	const [updateTagPopupVisible, setUpdateTagPopupVisible] = useState(false);
	const [selectedTag, setSelectedTag] = useState<Tag | undefined>();
	const tags = useTagStore(s => s.tags);

	const onTagSelected = (tag: Tag) => {
		setSelectedTag(tag);
		setUpdateTagPopupVisible(true);
	};

	return (
		<div className="text-left">
			<h4 className="font-semibold mb-2">Tags</h4>
			<Button onClick={() => setNewTagPopupVisible(true)}>Add New</Button>
			<NewTagPopup open={newTagPopupVisible} onOpenChange={setNewTagPopupVisible} />
			<Separator className="my-4" />
			{selectedTag && (
				<UpdateTagPopup open={updateTagPopupVisible} onOpenChange={setUpdateTagPopupVisible} tag={selectedTag} />
			)}
			<div className="inline-flex flex-wrap gap-2.5 max-h-[300px] overflow-auto">
				{tags.map(tag => (
					<div key={tag.id} onClick={() => onTagSelected(tag)}>
						<TagBadge tag={tag} removable />
					</div>
				))}
			</div>
			<Separator className="my-4" />
		</div>
	);
}

// src/components/Family/Settings/TagsSettings.vue
<template>
	<h4>Tags</h4>
	<a-button type="primary" @click="newTagPopupIsVisibile = true"> Add New </a-button>
	<NewTagPopup :visible="newTagPopupIsVisibile" @close="newTagPopupIsVisibile = false" />
	<a-divider />
	<UpdateTagPopup
		:visible="updateTagPopupIsVisibile"
		:tag="selectedTag"
		@close="updateTagPopupIsVisibile = false"
	/>
	<div class="flex-gap" style="max-height: 300px; overflow: auto">
		<TagBadge :removable="true" :tag="tag" @click="onTagSelected(tag)" v-for="tag in tags" />
	</div>
	<a-divider />
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { Tag } from '../../../models/tag';
import { useTagStore } from '../../../stores/tag';
import NewTagPopup from './NewTagPopup.vue';
import TagBadge from '../../Badges/Tag.vue';
import UpdateTagPopup from './UpdateTagPopup.vue';

const newTagPopupIsVisibile = ref(false);

const tags = computed(() => useTagStore().tags);

const updateTagPopupIsVisibile = ref(false);
const selectedTag = ref<Tag>();
const onTagSelected = (tag: Tag) => {
	selectedTag.value = tag;
	updateTagPopupIsVisibile.value = true;
};
</script>
