// src/components/Family/Settings/UpdateTagPopup.tsx
import { useEffect, useState } from "react";
import { DataBaseClient } from "../../../api/db";
import type { Tag } from "../../../models/tag";
import {
	openNotificationWithIcon,
	setIsLoading,
} from "../../../services/utils";
import { useTagStore } from "../../../stores/tag";
import { Badge } from "../../ui/badge";
import { Button } from "../../ui/button";
import {
	Dialog,
	DialogContent,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "../../ui/dialog";
import { Input } from "../../ui/input";
import { Separator } from "../../ui/separator";

interface Props {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	tag: Tag;
}

export default function UpdateTagPopup({
	open,
	onOpenChange,
	tag: propTag,
}: Props) {
	const [tag, setTag] = useState<Tag>(JSON.parse(JSON.stringify(propTag)));
	useEffect(() => {
		setTag(JSON.parse(JSON.stringify(propTag)));
	}, [propTag]);
	const updateField = (field: string, value: any) =>
		setTag((prev) => ({ ...prev, [field]: value }));

	const handleOk = () => {
		setIsLoading(true);
		DataBaseClient.Tag.update(tag)
			.then(() => {
				openNotificationWithIcon(
					"success",
					"Success",
					"Tag " + tag.name + " updated",
				);
				useTagStore.getState().updateTag(tag);
				onOpenChange(false);
			})
			.catch((err) => console.error(err))
			.finally(() => setIsLoading(false));
	};

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>Modify Tag</DialogTitle>
				</DialogHeader>
				<div className="flex flex-col gap-3 items-start">
					<div className="w-full">
						<p className="text-sm mb-1">Name</p>
						<Input
							type="text"
							value={tag.name}
							onChange={(e) => updateField("name", e.target.value)}
							placeholder="Ex. ABC23"
							maxLength={5}
						/>
					</div>
					<div className="w-full">
						<p className="text-sm mb-1">Description</p>
						<Input
							type="text"
							value={tag.description || ""}
							onChange={(e) => updateField("description", e.target.value)}
							placeholder="Optional description"
						/>
					</div>
					<div>
						<p className="text-sm mb-1">Color</p>
						<input
							type="color"
							value={tag.color || "#ababab"}
							onChange={(e) => updateField("color", e.target.value)}
							className="h-10 w-10 cursor-pointer"
						/>
					</div>
				</div>
				<Separator />
				<div className="grid grid-cols-2 gap-4">
					<div className="flex items-center justify-around">
						<p className="text-sm">Previous</p>
						<Badge style={{ backgroundColor: propTag.color, color: "white" }}>
							{propTag.name}
						</Badge>
					</div>
					{tag.name && (
						<div className="flex items-center justify-around">
							<p className="text-sm">Preview</p>
							<Badge style={{ backgroundColor: tag.color, color: "white" }}>
								{tag.name}
							</Badge>
						</div>
					)}
				</div>
				<DialogFooter>
					<Button variant="outline" onClick={() => onOpenChange(false)}>
						Cancel
					</Button>
					<Button onClick={handleOk} disabled={!tag.name}>
						Update
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

// src/components/Family/Settings/UpdateTagPopup.vue
<template>
	<a-modal
		v-model:visible="visible"
		title="Modify Tag"
		@cancel="emits('close')"
		:loading="loading"
		:disabled="true"
	>
		<div class="input-form center">
			<a-row class="full-width" style="margin-top: 10px">
				<p>Name</p>
				<a-input
					class="full-width"
					type="text"
					v-model:value="tag.name"
					placeholder="Ex. ABC23"
					:maxlength="5"
				/>
			</a-row>
			<a-row class="full-width" style="margin-top: 10px">
				<p>Description</p>
				<a-input
					name="description"
					class="full-width"
					type="text"
					v-model:value="tag.description"
					placeholder="Optional description"
				/>
			</a-row>
			<a-row class="full-width flex-center" style="margin-top: 10px">
				<a-col :span="10">
					<p>Color</p>
					<a-input
						name="color"
						type="color"
						v-model:value="tag.color"
						placeholder="Background color"
					></a-input>
				</a-col>
			</a-row>
		</div>
		<a-divider></a-divider>
		<a-row v-if="props.tag">
			<a-col :span="12">
				<div class="tag-preview flex-center">
					<p>Previous</p>
					<a-tooltip>
						<template #title v-if="props.tag.description">{{
							props.tag.description
						}}</template>
						<a-tag :color="props.tag.color" size="large">{{ props.tag.name }}</a-tag>
					</a-tooltip>
				</div>
			</a-col>
			<a-col :span="12">
				<div class="tag-preview flex-center" v-if="tag.name">
					<p>Preview</p>
					<a-tooltip>
						<template #title v-if="tag.description">{{ tag.description }}</template>
						<a-tag :color="tag.color" size="large">{{ tag.name }}</a-tag>
					</a-tooltip>
				</div>
			</a-col>
		</a-row>
		<template #footer>
			<a-button key="back" @click="emits('close')">Cancel</a-button>
			<a-button
				key="submit"
				type="primary"
				:loading="loading"
				@click="handleOk"
				:disabled="!tag.name"
				>Update</a-button
			>
		</template>
	</a-modal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { Tag } from '../../../models/tag';
import { loading, openNotificationWithIcon, setIsLoading } from '../../../services/utils';
import { DataBaseClient } from '../../../api/db';
import { useTagStore } from '../../../stores/tag';

const props = defineProps<{
	visible: boolean;
	tag?: Tag;
}>();
const emits = defineEmits(['close', 'ok']);

const visible = ref<boolean>(false);
const tag = ref<Tag>(JSON.parse(JSON.stringify(props.tag || {})));

watch(
	() => props.visible,
	() => (visible.value = props.visible)
);
watch(
	() => props.tag,
	() => (tag.value = JSON.parse(JSON.stringify(props.tag || {})))
);
watch(
	() => visible.value,
	() => {
		if (!visible.value) emits('close');
	}
);

const handleOk = () => {
	setIsLoading(true);
	DataBaseClient.Tag.update(tag.value)
		.then(() => {
			openNotificationWithIcon('success', 'Success', 'Tag ' + tag.value.name + ' updated');
			useTagStore().updateTag(tag.value);
			emits('close');
		})
		.catch(err => console.error(err))
		.finally(() => setIsLoading(false));
};
</script>

<style lang="scss" scoped>
.input-form {
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	align-items: flex-start;
}
.tag-preview {
	justify-content: space-around;
	p {
		margin-bottom: 0;
	}
}
</style>
